### ISSUE TITLE
SSL issue when building Jenkins work around

### ISSUE THREAD

**Issue by bobbui** [Alien2150/til#1]
get this error when try to build docker image:
```
Retrieving update center information
Created cache at: /var/jenkins_home/.cache/jenkins-plugin-management-cli
Cache miss for: update-center-2.249.3
Cache miss for: experimental-update-center-2.249.3
Cache miss for: plugin-versions
io.jenkins.tools.pluginmanager.impl.UpdateCenterInfoRetrievalException: Error getting update center json
	at io.jenkins.tools.pluginmanager.impl.PluginManager.getJson(PluginManager.java:578)
	at io.jenkins.tools.pluginmanager.impl.PluginManager.getUCJson(PluginManager.java:603)
	at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:146)
	at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:113)
	at io.jenkins.tools.pluginmanager.cli.Main.main(Main.java:63)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1310)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1151)
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1054)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:394)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2739)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2651)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1830)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at java.net.URL.openStream(URL.java:1068)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:2795)
	at io.jenkins.tools.pluginmanager.impl.PluginManager.getJson(PluginManager.java:572)
	... 4 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:167)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1143)
	... 16 more
Error getting update center json
```
Any idea on how to fix it?
Thanks

**Comment by bobbui** [comment]
solved by tweak the download command as follow:
RUN JENKINS_UC_DOWNLOAD=http://mirrors.jenkins-ci.org JENKINS_UC_EXPERIMENTAL=https://updates.jenkins.io/experimental jenkins-plugin-cli --verbose -f /usr/share/jenkins/ref/plugins.txt
